torchrun --standalone --nproc_per_node 2 torchrun_main.py \
    --model_name 60m_scale \
    --model_config configs/llama_60m.json \
    --optimizer scale \
    --lr 1e-3 \
    --momentum 0.9 \
    --weight_decay 0.0 \
    --batch_size 256 \
    --total_batch_size 512 \
    --num_training_steps 11000 \
    --warmup_steps 1100 \
    --dtype bfloat16 \
    --eval_every 1000 \
    --save_every 1000 \
    --seed 42  \
    --scheduler cosine \
    --dataset_path /path/to/c4/en \
    --hf_dataset